"""Markdown export — mirrors lib/export.ts."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from cli_anything.nodepad.core.content_types import TYPE_ORDER, CONTENT_TYPE_META
from cli_anything.nodepad.core.project import Project, TextBlock


def _md_cell(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def _format_date(ts: float | None = None) -> str:
    d = datetime.fromtimestamp(ts / 1000) if ts else datetime.now()
    return d.strftime("%-d %B %Y")


def _format_time(ts: float | None = None) -> str:
    if not ts:
        return ""
    return datetime.fromtimestamp(ts / 1000).strftime("%H:%M")


def _confidence_bar(c: float) -> str:
    pct = round(c)
    filled = round(c / 20)  # 0-100 -> 0-5
    bar = "\u2588" * filled + "\u2591" * (5 - filled)
    return f"{bar} {pct}%"


def _slug(text: str) -> str:
    import re
    s = text.lower()
    s = re.sub(r"[^a-z0-9\s-]", "", s).strip()
    s = re.sub(r"\s+", "-", s)
    return s[:50]


def export_to_markdown(project: Project) -> str:
    """Export a project as richly-formatted Markdown."""
    blocks = project.blocks
    name = project.name

    if not blocks:
        return f"# {name}\n\n> _No nodes yet._\n\n---\n*Generated by [nodepad](https://nodepad.space)*\n"

    # Group by type
    by_type: dict[str, list[TextBlock]] = {}
    for b in blocks:
        t = b.content_type or "general"
        by_type.setdefault(t, []).append(b)

    present_types = [t for t in TYPE_ORDER if t in by_type]
    date = _format_date(blocks[0].timestamp if blocks else None)
    pinned = [b for b in blocks if b.is_pinned]

    lines: list[str] = []

    # YAML front matter
    lines.append("---")
    lines.append(f'title: "{name}"')
    lines.append(f'date: "{date}"')
    lines.append(f"nodes: {len(blocks)}")
    types_str = ", ".join(f'"{t}"' for t in present_types)
    lines.append(f"types: [{types_str}]")
    lines.append("source: nodepad \u2014 https://nodepad.space")
    lines.append("---")
    lines.append("")

    # Title
    lines.append(f"# {name}")
    lines.append("")
    lines.append(f"> **Generated by [nodepad](https://nodepad.space)** \u00b7 {date} \u00b7 {len(blocks)} node{'s' if len(blocks) != 1 else ''}")
    lines.append("")

    # Stats table
    lines.append("## Overview")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|------|-------|")
    for t in present_types:
        meta = CONTENT_TYPE_META.get(t, {"emoji": "", "label": t})
        lines.append(f"| {meta['emoji']} {meta.get('label', t)} | {len(by_type[t])} |")
    lines.append("")

    # Pinned
    if pinned:
        lines.append("> **\U0001f4cc Pinned nodes**")
        for b in pinned:
            lines.append(f"> - {b.text}")
        lines.append("")

    # TOC
    lines.append("## Contents")
    lines.append("")
    for t in present_types:
        meta = CONTENT_TYPE_META.get(t, {"emoji": "", "label": t})
        label = meta.get("label", t)
        count = len(by_type[t])
        lines.append(f"- [{meta['emoji']} {label}](#{_slug(label)}) *({count})*")
    lines.append("")

    # Sections
    for t in present_types:
        group = by_type[t]
        meta = CONTENT_TYPE_META.get(t, {"emoji": "", "label": t, "description": ""})
        label = meta.get("label", t)

        lines.append("---")
        lines.append("")
        lines.append(f"## {meta['emoji']} {label}")
        lines.append("")
        lines.append(f"*{meta.get('description', '')}*")
        lines.append("")

        if t == "claim":
            lines.append("| Claim | Category | Confidence | AI Annotation |")
            lines.append("|-------|----------|------------|---------------|")
            for b in group:
                cat = f"`{_md_cell(b.category)}`" if b.category else "\u2014"
                conf = f"`{_confidence_bar(b.confidence)}`" if b.confidence is not None else "\u2014"
                annot = b.annotation.replace("\n", " ").replace("|", "\\|")[:120] + ("\u2026" if b.annotation and len(b.annotation) > 120 else "") if b.annotation else "\u2014"
                lines.append(f"| **{b.text.replace('|', '\\|')}** | {cat} | {conf} | {annot} |")
            lines.append("")
            continue

        if t == "task":
            for b in group:
                lines.append(f"- [ ] **{b.text}**")
                if b.category:
                    lines.append(f"  - Category: `{b.category}`")
                if b.annotation:
                    lines.append(f"  - > {b.annotation.replace(chr(10), ' ')}")
            lines.append("")
            continue

        if t == "quote":
            for b in group:
                lines.append(f"> {b.text}")
                if b.category:
                    lines.append(">")
                    lines.append(f"> \u2014 `{b.category}`")
                if b.annotation:
                    lines.append(">")
                    lines.append(f"> *{b.annotation.replace(chr(10), ' ')}*")
                lines.append("")
            continue

        # All other types
        for b in group:
            lines.append(f"### {b.text}")
            lines.append("")
            meta_parts: list[str] = []
            if b.category:
                meta_parts.append(f"**Category:** `{b.category}`")
            if b.timestamp:
                meta_parts.append(f"**Added:** {_format_date(b.timestamp)} {_format_time(b.timestamp)}")
            if b.is_pinned:
                meta_parts.append("\U0001f4cc *Pinned*")
            if meta_parts:
                lines.append(" \u00b7 ".join(meta_parts))
                lines.append("")
            if b.annotation:
                lines.append("> **AI Annotation**")
                for l in b.annotation.split("\n"):
                    lines.append(f"> {l}")
                lines.append("")
            if b.sources:
                lines.append("**Sources**")
                lines.append("")
                for s in b.sources:
                    label = s.title or s.site_name or s.url
                    site = f" *({s.site_name})*" if s.site_name else ""
                    lines.append(f"- [{label}]({s.url}){site}")
                lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by [nodepad](https://nodepad.space) \u00b7 {date}*")
    lines.append("")

    return "\n".join(lines)
